// Standard GST UQC (Unit Quantity Codes) — 44 codes
// Ref: https://cleartax.in/s/gst-unit-quantity-code-uqc

type Uqc = { code: string; label: string }

export const UQC_CODES: Uqc[] = [
  { code: 'BAG', label: 'Bags' },
  { code: 'BAL', label: 'Bale' },
  { code: 'BDL', label: 'Bundles' },
  { code: 'BKL', label: 'Buckles' },
  { code: 'BOU', label: 'Billions of units' },
  { code: 'BOX', label: 'Box' },
  { code: 'BTL', label: 'Bottles' },
  { code: 'BUN', label: 'Bunches' },
  { code: 'CAN', label: 'Cans' },
  { code: 'CBM', label: 'Cubic meter' },
  { code: 'CCM', label: 'Cubic centimeter' },
  { code: 'CMS', label: 'Centimeter' },
  { code: 'CTN', label: 'Cartons' },
  { code: 'DOZ', label: 'Dozen' },
  { code: 'DRM', label: 'Drum' },
  { code: 'GGR', label: 'Great gross' },
  { code: 'GMS', label: 'Grams' },
  { code: 'GRS', label: 'Gross' },
  { code: 'GYD', label: 'Gross yards' },
  { code: 'KGS', label: 'Kilograms' },
  { code: 'KLR', label: 'Kiloliter' },
  { code: 'KME', label: 'Kilometre' },
  { code: 'MLT', label: 'Millilitre' },
  { code: 'MTR', label: 'Meters' },
  { code: 'MTS', label: 'Metric tons' },
  { code: 'NOS', label: 'Numbers' },
  { code: 'PAC', label: 'Packs' },
  { code: 'PCS', label: 'Pieces' },
  { code: 'PRS', label: 'Pairs' },
  { code: 'QTL', label: 'Quintal' },
  { code: 'ROL', label: 'Rolls' },
  { code: 'SET', label: 'Sets' },
  { code: 'SQF', label: 'Square feet' },
  { code: 'SQM', label: 'Square meters' },
  { code: 'SQY', label: 'Square yards' },
  { code: 'TBS', label: 'Tablets' },
  { code: 'TGM', label: 'Ten gross' },
  { code: 'THD', label: 'Thousands' },
  { code: 'TON', label: 'Tonnes' },
  { code: 'TUB', label: 'Tubes' },
  { code: 'UGS', label: 'US gallons' },
  { code: 'UNT', label: 'Units' },
  { code: 'YDS', label: 'Yards' },
  { code: 'OTH', label: 'Others' },
]
